### ISSUE TITLE
Parameter [TZID] is not applicable

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/ics-import-export#22] opened 2015-09-08 18:35 UTC
```
  2038           SaveCalendar  E  SaveCalendar
  2038           SaveCalendar  E  net.fortuna.ical4j.model.ValidationException: Parameter [TZID] is not applicable
  2038           SaveCalendar  E  at net.fortuna.ical4j.util.ParameterValidator.assertNone(ParameterValidator.java:109)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.property.DateProperty.validate(DateProperty.java:234)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.property.DtStart.validate(DtStart.java:194)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.Component.validateProperties(Component.java:219)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.component.VEvent.validate(VEvent.java:472)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.Component.validate(Component.java:201)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.Calendar.validateComponents(Calendar.java:500)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.Calendar.validate(Calendar.java:478)
  2038           SaveCalendar  E  at net.fortuna.ical4j.model.Calendar.validate(Calendar.java:257)
  2038           SaveCalendar  E  at net.fortuna.ical4j.data.CalendarOutputter.output(CalendarOutputter.java:96)
  2038           SaveCalendar  E  at net.fortuna.ical4j.data.CalendarOutputter.output(CalendarOutputter.java:83)
  2038           SaveCalendar  E  at org.sufficientlysecure.ical.SaveCalendar.run(SaveCalendar.java:188)
  2038           SaveCalendar  E  at org.sufficientlysecure.ical.ui.dialogs.RunnableWithProgress$1.run(RunnableWithProgress.java:49)
  2038           SaveCalendar  E  at java.lang.Thread.run(Thread.java:818)
  755           WindowManager  V  not Base app: Adding window Window{513f02c u0 org.sufficientlysecure.ical/org.sufficientlysecure.ical.ui.MainActivity} at 17 of 22
```

**Comment by dschuermann** [comment] 2015-09-08 18:45
I haven't figured out which entry it was...

**Comment by dschuermann** [comment] 2015-09-08 20:01
No timezone parameter TZID must be appended if the timezone is UTC.

**Comment by jgriffiths** [comment] 2015-09-09 13:14
Can you uncomment the lines:

        //String cursorContents = DatabaseUtils.dumpCurrentRowToString(cur);
        //Log.d(TAG, "cursor: " + cursorContents);

In SaveCalendar.java, add 'import android.database.DatabaseUtils;' to the top and re-run?

That will tell you what event and most importantly what values were being used, if you could post them here after redacting any personal info.

**Comment by dschuermann** [comment] 2015-09-09 14:04
I am still not sure which entry it was but I searched for "UTC" inside the log file and found something like this:
```
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m cursor: 2604 {
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m _id=60135
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m original_id=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m uid2445=memotooEvent11465979
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m title=Itis akkr
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m description=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m organizer=dominik@dominikschuermann.de
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m eventLocation=Iz 404
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m eventStatus=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m allDay=0
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m rdate=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m rrule=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m dtstart=1304414100000
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m eventTimezone=Etc/UTC
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m duration=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m dtend=1304417700000
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m eventEndTimezone=Etc/UTC
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m accessLevel=3
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m availability=0
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m exdate=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m exrule=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m customAppPackage=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m customAppUri=null
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m hasAlarm=0
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m }
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m Adding event: BEGIN:VEVENT
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m DTSTAMP:20150909T135809Z
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m UID:memotooEvent11465979
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m SUMMARY:Itis akkr
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m ORGANIZER:dominik@dominikschuermann.de
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m LOCATION:Iz 404
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m DTSTART;TZID=Europe/London:20110503T101500
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m DTEND;TZID=Europe/London:20110503T111500
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m CLASS:PUBLIC
[37m[40m[2m 30009  [0m [34m[2m        SaveCalendar[0m [30m[44m D [0m END:VEVENT
```

**Comment by dschuermann** [comment] 2015-09-09 14:05
Shouldn't this use the DSTART and DEND values with "Z" in the end for UTC?

**Comment by jgriffiths** [comment] 2015-09-09 22:05
Thanks for the debug info, let me know if the above doesn't fix it.

**Comment by dschuermann** [comment] 2015-09-10 08:09
Still not working. I looked through all my entries and android always uses "Etc/UTC" for me.

Maybe this is a failure: It has "DTSTART;TZID=Europe/Berlin:20140427T080000Z". I thought a "Z" in the end indicates UTC, but it also specifies a timezone.

```
D/SaveCalendar( 8375): cursor: 702 {
D/SaveCalendar( 8375):    _id=58233
D/SaveCalendar( 8375):    original_id=null
D/SaveCalendar( 8375):    uid2445=c736be18-f7dc-441e-8a1e-174f5c818ced
D/SaveCalendar( 8375):    title=test
D/SaveCalendar( 8375):    description=null
D/SaveCalendar( 8375):    organizer=dominik@dominikschuermann.de
D/SaveCalendar( 8375):    eventLocation=null
D/SaveCalendar( 8375):    eventStatus=1
D/SaveCalendar( 8375):    allDay=0
D/SaveCalendar( 8375):    rdate=null
D/SaveCalendar( 8375):    rrule=null
D/SaveCalendar( 8375):    dtstart=1398585600000
D/SaveCalendar( 8375):    eventTimezone=Europe/Berlin
D/SaveCalendar( 8375):    duration=null
D/SaveCalendar( 8375):    dtend=1398596400000
D/SaveCalendar( 8375):    eventEndTimezone=Europe/Berlin
D/SaveCalendar( 8375):    accessLevel=0
D/SaveCalendar( 8375):    availability=1
D/SaveCalendar( 8375):    exdate=null
D/SaveCalendar( 8375):    exrule=null
D/SaveCalendar( 8375):    customAppPackage=null
D/SaveCalendar( 8375):    customAppUri=null
D/SaveCalendar( 8375):    hasAlarm=1
D/SaveCalendar( 8375): }
D/SaveCalendar( 8375): Adding event: BEGIN:VEVENT
D/SaveCalendar( 8375): DTSTAMP:20150910T074807Z
D/SaveCalendar( 8375): UID:c736be18-f7dc-441e-8a1e-174f5c818ced
D/SaveCalendar( 8375): SUMMARY:test
D/SaveCalendar( 8375): ORGANIZER:dominik@dominikschuermann.de
D/SaveCalendar( 8375): STATUS:CONFIRMED
D/SaveCalendar( 8375): DTSTART;TZID=Europe/Berlin:20140427T080000Z
D/SaveCalendar( 8375): DTEND;TZID=Europe/Berlin:20140427T110000Z
D/SaveCalendar( 8375): BEGIN:VALARM
D/SaveCalendar( 8375): TRIGGER:-PT15M
D/SaveCalendar( 8375): ACTION:DISPLAY
D/SaveCalendar( 8375): DESCRIPTION:Umzug Stas helfen
D/SaveCalendar( 8375): END:VALARM
D/SaveCalendar( 8375): END:VEVENT
```

**Comment by jgriffiths** [comment] 2015-09-10 10:22
OK, so there are two issues I think. The first is that there are multiple aliases for the UTC timezone which need to be recognised so we treat them as UTC instead of adding the alias as an explicit TZ which would fail the validation rule. The 2 patches above should cover that.

I think the DTSTART;TZID=Europe/Berlin:20140427T080000Z case is due to the way I construct the date, as UTC first and then setting a TZ - which should un-mark it as UTC but doesn't appear to. I will try changing the construction to avoid creating a UTC date first and adding a TZ later.

**Comment by dschuermann** [comment] 2015-09-11 11:25
Just retestet with current master. I still get the same problem and the mentioned entry.

**Comment by jgriffiths** [comment] 2015-09-11 13:24
This makes no sense. Here is what i get trying to reproduce this issue:

ICS_SaveCalendar﹕ cursor: 0 {
    _id=6482
    original_id=null
    uid2445=foobarlkjhdsfsdfadw
    title=Märchenerzähler 2
    description=Märchenerzähler Event 2
    organizer=Local Calendar
    eventLocation=null
    eventStatus=null
    allDay=0
    rdate=null
    rrule=null
    dtstart=1398578400000
    eventTimezone=Europe/Berlin
    duration=null
    dtend=1398589200000
    eventEndTimezone=Europe/Berlin
    accessLevel=0
    availability=0
    exdate=null
    exrule=null
    customAppPackage=null
    customAppUri=null
    hasAlarm=0
    }
ICS_SaveCalendar﹕ getDateTime from tz: dtstart->1398578400000
ICS_SaveCalendar﹕ getDateTime non-UTC tz: 'Europe/Berlin'
ICS_SaveCalendar﹕ getDateTime from tz: dtend->1398589200000
ICS_SaveCalendar﹕ getDateTime non-UTC tz: 'Europe/Berlin'

ICS_SaveCalendar﹕ Adding event: BEGIN:VEVENT
    DTSTAMP:20150911T130450Z
    UID:foobarlkjhdsfsdfadw
    SUMMARY:Märchenerzähler 2
    DESCRIPTION:Märchenerzähler Event 2
    DTSTART;TZID=Europe/Berlin:20140427T080000
    DTEND;TZID=Europe/Berlin:20140427T110000
    END:VEVENT

The only values which can affect DTSTART are:
- allDay (both 0, i.e. false)
- dtstart=Both valid dates
- eventTimezone: Both Europe/Berlin

So I don't see how this can happen :(

**Comment by jgriffiths** [comment] 2015-09-11 13:27
@dschuermann can you sync to 6e2f2e8c0d6a958175146e389eb9cdcd4cbbadab, enable verbose logging in the settings and re-try?

That commit contains a hack to validate the event as it is created, so hopefully the error will be found immediately and there should be more logging there too.

**Comment by dschuermann** [comment] 2015-09-11 13:38
It stopped exactly for the mentioned entry:
```
  1982       ICS_SaveCalendar  D  cursor: 702 {
  1982       ICS_SaveCalendar  D  _id=58233
  1982       ICS_SaveCalendar  D  original_id=null
  1982       ICS_SaveCalendar  D  uid2445=c736be18-f7dc-441e-8a1e-174f5c818ced
  1982       ICS_SaveCalendar  D  title=test
  1982       ICS_SaveCalendar  D  description=null
  1982       ICS_SaveCalendar  D  organizer=dominik@dominikschuermann.de
  1982       ICS_SaveCalendar  D  eventLocation=null
  1982       ICS_SaveCalendar  D  eventStatus=1
  1982       ICS_SaveCalendar  D  allDay=0
  1982       ICS_SaveCalendar  D  rdate=null
  1982       ICS_SaveCalendar  D  rrule=null
  1982       ICS_SaveCalendar  D  dtstart=1398585600000
  1982       ICS_SaveCalendar  D  eventTimezone=Europe/Berlin
  1982       ICS_SaveCalendar  D  duration=null
  1982       ICS_SaveCalendar  D  dtend=1398596400000
  1982       ICS_SaveCalendar  D  eventEndTimezone=Europe/Berlin
  1982       ICS_SaveCalendar  D  accessLevel=0
  1982       ICS_SaveCalendar  D  availability=1
  1982       ICS_SaveCalendar  D  exdate=null
  1982       ICS_SaveCalendar  D  exrule=null
  1982       ICS_SaveCalendar  D  customAppPackage=null
  1982       ICS_SaveCalendar  D  customAppUri=null
  1982       ICS_SaveCalendar  D  hasAlarm=1
  1982       ICS_SaveCalendar  D  }
  1982       ICS_SaveCalendar  D  getDateTime from tz: dtstart->1398585600000
  1982       ICS_SaveCalendar  D  getDateTime non-UTC tz: 'Europe/Berlin'
  1982       ICS_SaveCalendar  D  getDateTime from tz: dtend->1398596400000
  1982       ICS_SaveCalendar  D  getDateTime non-UTC tz: 'Europe/Berlin'
  1982   RunnableWithProgress  E  An exception occurred
  1982   RunnableWithProgress  E  net.fortuna.ical4j.model.ValidationException: Parameter [TZID] is not applicable
  1982   RunnableWithProgress  E  at net.fortuna.ical4j.util.ParameterValidator.assertNone(ParameterValidator.java:109)
  1982   RunnableWithProgress  E  at net.fortuna.ical4j.model.property.DateProperty.validate(DateProperty.java:234)
  1982   RunnableWithProgress  E  at net.fortuna.ical4j.model.property.DtStart.validate(DtStart.java:194)
  1982   RunnableWithProgress  E  at net.fortuna.ical4j.model.Component.validateProperties(Component.java:219)
  1982   RunnableWithProgress  E  at net.fortuna.ical4j.model.component.VEvent.validate(VEvent.java:472)
  1982   RunnableWithProgress  E  at org.sufficientlysecure.ical.SaveCalendar.runImpl(SaveCalendar.java:174)
  1982   RunnableWithProgress  E  at org.sufficientlysecure.ical.ui.dialogs.RunnableWithProgress.run(RunnableWithProgress.java:85)
  1982   RunnableWithProgress  E  at org.sufficientlysecure.ical.ui.dialogs.RunnableWithProgress$1.run(RunnableWithProgress.java:53)
  1982   RunnableWithProgress  E  at java.lang.Thread.run(Thread.java:818)
```

**Comment by jgriffiths** [comment] 2015-09-11 14:00
Thanks, I appreciate your patience with this bug!

Could you please sync to 46704bcbde1c4eb59b8c87a9352a55e347c2dba7 and re-try?

That commit will throw once the date considers itself UTC showing which method is going wrong.

**Comment by dschuermann** [comment] 2015-09-11 14:13
np, I am interesting in getting this fixed, great work!

Unfortunatly, no RuntimeException :/
```
 5550       ICS_SaveCalendar  D  cursor: 702 {
  5550       ICS_SaveCalendar  D  _id=58233
  5550       ICS_SaveCalendar  D  original_id=null
  5550       ICS_SaveCalendar  D  uid2445=c736be18-f7dc-441e-8a1e-174f5c818ced
  5550       ICS_SaveCalendar  D  title=Umzug Stas helfen
  5550       ICS_SaveCalendar  D  description=null
  5550       ICS_SaveCalendar  D  organizer=dominik@dominikschuermann.de
  5550       ICS_SaveCalendar  D  eventLocation=null
  5550       ICS_SaveCalendar  D  eventStatus=1
  5550       ICS_SaveCalendar  D  allDay=0
  5550       ICS_SaveCalendar  D  rdate=null
  5550       ICS_SaveCalendar  D  rrule=null
  5550       ICS_SaveCalendar  D  dtstart=1398585600000
  5550       ICS_SaveCalendar  D  eventTimezone=Europe/Berlin
  5550       ICS_SaveCalendar  D  duration=null
  5550       ICS_SaveCalendar  D  dtend=1398596400000
  5550       ICS_SaveCalendar  D  eventEndTimezone=Europe/Berlin
  5550       ICS_SaveCalendar  D  accessLevel=0
  5550       ICS_SaveCalendar  D  availability=1
  5550       ICS_SaveCalendar  D  exdate=null
  5550       ICS_SaveCalendar  D  exrule=null
  5550       ICS_SaveCalendar  D  customAppPackage=null
  5550       ICS_SaveCalendar  D  customAppUri=null
  5550       ICS_SaveCalendar  D  hasAlarm=1
  5550       ICS_SaveCalendar  D  }
  5550       ICS_SaveCalendar  D  getDateTime from tz: dtstart->1398585600000
  5550       ICS_SaveCalendar  D  getDateTime non-UTC tz: 'Europe/Berlin'
  5550       ICS_SaveCalendar  D  getDateTime tz: Central European Standard Time
  5550       ICS_SaveCalendar  D  getDateTime from tz: dtend->1398596400000
  5550       ICS_SaveCalendar  D  getDateTime non-UTC tz: 'Europe/Berlin'
  5550       ICS_SaveCalendar  D  getDateTime tz: Central European Standard Time
  5550   RunnableWithProgress  E  An exception occurred
  5550   RunnableWithProgress  E  net.fortuna.ical4j.model.ValidationException: Parameter [TZID] is not applicable
  5550   RunnableWithProgress  E  at net.fortuna.ical4j.util.ParameterValidator.assertNone(ParameterValidator.java:109)
  5550   RunnableWithProgress  E  at net.fortuna.ical4j.model.property.DateProperty.validate(DateProperty.java:234)
  5550   RunnableWithProgress  E  at net.fortuna.ical4j.model.property.DtStart.validate(DtStart.java:194)
  5550   RunnableWithProgress  E  at net.fortuna.ical4j.model.Component.validateProperties(Component.java:219)
  5550   RunnableWithProgress  E  at net.fortuna.ical4j.model.component.VEvent.validate(VEvent.java:472)
  5550   RunnableWithProgress  E  at org.sufficientlysecure.ical.SaveCalendar.runImpl(SaveCalendar.java:174)
  5550   RunnableWithProgress  E  at org.sufficientlysecure.ical.ui.dialogs.RunnableWithProgress.run(RunnableWithProgress.java:85)
  5550   RunnableWithProgress  E  at org.sufficientlysecure.ical.ui.dialogs.RunnableWithProgress$1.run(RunnableWithProgress.java:53)
  5550   RunnableWithProgress  E  at java.lang.Thread.run(Thread.java:818)
``

**Comment by jgriffiths** [comment] 2015-09-11 14:45
I have reproduced it - should have a fix tomorrow, thanks for your help!

**Comment by jgriffiths** [comment] 2015-09-12 03:30
Should be fixed now, please re-open if not.

**Closed by jgriffiths** 2015-09-12 03:30 UTC

**Comment by dschuermann** [comment] 2015-09-13 14:57
:+1: works now
